/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

import view.MaQuaiTheme;
import model.KhachHang;
import model.QuanLyKhachHangService;
import util.TaiAnhGamePlay;
import util.TextFileStorage;
import view.UiKhachHang;
import view.UiPhuBanHang;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author lap top
 */
public class UIChinh extends javax.swing.JFrame {

    private TextFileStorage.PlayerData playerData;
    private Timer gameTimer;
    private long gameStartTime;
    private final float TIME_SCALE = 0.1f;
    private QuanLyKhachHangService khachHangService;
    private KhachHang khachHangTamThoi;
    private KhachHang khachHangMoiTamThoi;

    public UIChinh() {
        initComponents();
        customizeUI();
        loadPlayerData(); // Phải gọi trước
        khachHangService = new QuanLyKhachHangService(playerData); // Gọi sau khi có playerData
        updateUI();
        initGameTimer();
        loadRandomImageToButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAnh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnKHTrongNgay = new javax.swing.JButton();
        btnTTKH = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBan = new javax.swing.JButton();
        btnKhong = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cửa hàng hoang");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tên:");

        jLabel2.setText("Player");

        jLabel3.setText("Thời gian:");

        jLabel4.setText("00:00");

        jLabel5.setText("Tiền:");

        jLabel6.setText("0000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jButton1.setText("Cửa Hàng");
        jButton1.setActionCommand("btnShop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAnh.setText("jButton2");
        btnAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        btnKHTrongNgay.setText("KH trong ngày");
        btnKHTrongNgay.setToolTipText("");
        btnKHTrongNgay.setActionCommand("btnKHTrongNgay");
        btnKHTrongNgay.setName("btnKHTrongNgay"); // NOI18N
        btnKHTrongNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHTrongNgayActionPerformed(evt);
            }
        });

        btnTTKH.setText("Thông tin KH");
        btnTTKH.setToolTipText("");
        btnTTKH.setActionCommand("btnThongTinKH");
        btnTTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTKHActionPerformed(evt);
            }
        });

        jLabel7.setText("Điểm Tinh Thần Hiện Tại");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("100");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), null));

        btnBan.setText("bán");
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        btnKhong.setText("không");
        btnKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTTKH)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKhong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKHTrongNgay)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKHTrongNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(btnKhong))
                    .addComponent(btnBan))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setEnabled(false);

        SwingUtilities.invokeLater(() -> {
            UiPhuBanHang shop = new UiPhuBanHang(() -> {
                SwingUtilities.invokeLater(() -> {
                    loadPlayerData();
                    updateUI();
                    UIChinh.this.setEnabled(true);
                    UIChinh.this.toFront();
                });
            });

            shop.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            shop.setVisible(true);
        });
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new UIChinh().setVisible(true);
        });
    }

    private void loadPlayerData() {
        playerData = TextFileStorage.loadPlayerData();
        if (playerData.money <= 0) {
            playerData.money = 1000;
            playerData.mentalPoints = 100;
            playerData.inventory = new HashMap<>();
        }
    }

    private void updateUI() {
        jLabel6.setText(String.valueOf(playerData.money));
        jLabel8.setText(String.valueOf(playerData.mentalPoints));
    }

    private void initGameTimer() {
        gameStartTime = System.currentTimeMillis();
        gameTimer = new Timer(10, e -> updateGameTime());
        gameTimer.start();
    }

    private void updateGameTime() {
        long realTimeElapsed = System.currentTimeMillis() - gameStartTime;
        long gameTimeElapsed = (long) (realTimeElapsed * TIME_SCALE);
        long totalSeconds = gameTimeElapsed / 10;
        long minutes = (totalSeconds / 6) % 60;
        long hours = totalSeconds / 360;
        String timeString = String.format("%02d:%02d", hours, minutes);
        SwingUtilities.invokeLater(() -> {
            jLabel4.setText(timeString);
        });

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKHTrongNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHTrongNgayActionPerformed
        try {
            SwingUtilities.invokeLater(() -> {
                UiKhachHang giaoDienKH = new UiKhachHang();
                giaoDienKH.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                giaoDienKH.setVisible(true);
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi mở giao diện khách hàng: " + e.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKHTrongNgayActionPerformed

    private void btnAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhActionPerformed
        // Chỉ tạo khách hàng mới nếu không có khách hàng tạm thời nào đang chờ
        if (khachHangMoiTamThoi == null) {
            // Tạo khách hàng mới và gán vào biến tạm thời
            khachHangMoiTamThoi = khachHangService.taoKhachHangMoi();

            if (khachHangMoiTamThoi != null) {
                String yeuCau = khachHangMoiTamThoi.getTen() + " nói: " + khachHangService.layYeuCauKhachHangHienTai();

                // Hiển thị yêu cầu khách hàng qua JOptionPane
                JOptionPane.showMessageDialog(
                        this,
                        yeuCau,
                        "Khách hàng mới",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        } else {
            // Thông báo cho người dùng rằng có khách hàng đang chờ
            JOptionPane.showMessageDialog(this, "Có một khách hàng đang chờ rồi!", "Lỗi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAnhActionPerformed

    private void btnTTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTKHActionPerformed
        if (khachHangMoiTamThoi != null) {
            // Cập nhật khách hàng hiện tại trong service
            khachHangService.setKhachHangHienTai(khachHangMoiTamThoi);

            // Lấy thông tin khách hàng kèm yêu cầu dựa trên inventory hiện tại
            String thongTin = khachHangMoiTamThoi.layThongTin();
            String yeuCau = khachHangService.layYeuCauKhachHangHienTai();

            // Kiểm tra xem người chơi có đủ vật phẩm không
            String trangThai = khachHangService.kiemTraDuVatPham(playerData.inventory);

            // Hiển thị thông tin đầy đủ
            String thongTinDayDu = thongTin + "\n\nYÊU CẦU: " + yeuCau + "\n\nTRẠNG THÁI: " + trangThai;

            JOptionPane.showMessageDialog(this, thongTinDayDu, "Thông Tin Khách Hàng", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Chưa có khách hàng nào!", "Lỗi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTTKHActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        if (khachHangMoiTamThoi != null) {
            khachHangService.setKhachHangHienTai(khachHangMoiTamThoi);

            if (!khachHangService.kiemTraCoTheBan(playerData.inventory)) {
                JOptionPane.showMessageDialog(this,
                        "Không thể bán! Bạn không có đủ vật phẩm mà khách hàng yêu cầu.",
                        "Không thể bán",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            boolean result = khachHangService.xuLyBanHang(true, playerData.inventory);
            if (result) {
                // CẬP NHẬT TIỀN NGAY LẬP TỨC
                loadPlayerData();
                updateUI();
                loadRandomImageToButton();
                khachHangMoiTamThoi = null;
            }
        }
        jPanel2.setPreferredSize(new Dimension(700, 600));

    }//GEN-LAST:event_btnBanActionPerformed

    private void btnKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongActionPerformed
        if (khachHangMoiTamThoi != null) {
            khachHangService.setKhachHangHienTai(khachHangMoiTamThoi);

            // SỬA DÒNG NÀY: thêm playerData.inventory
            boolean result = khachHangService.xuLyBanHang(false, playerData.inventory);
            if (result) {
                updateUI();
                loadRandomImageToButton();
                khachHangMoiTamThoi = null;

            }
            jPanel2.setPreferredSize(new Dimension(700, 600));
        }
    }//GEN-LAST:event_btnKhongActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh;
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnKHTrongNgay;
    private javax.swing.JButton btnKhong;
    private javax.swing.JButton btnTTKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private void customizeUI() {
        JPanel[] panels = {jPanel1, jPanel2, jPanel3, jPanel4};
        JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8};
        JButton[] specialButtons = {btnKHTrongNgay, jButton1}; // Các nút màu đỏ máu
        JButton[] normalButtons = {btnTTKH}; // Các nút màu xanh rêu

        MaQuaiTheme.applyTheme(this, panels, labels, specialButtons, normalButtons);

        // Custom thêm nếu cần
        jLabel2.setFont(new Font("Dialog", Font.BOLD, 14));
        jLabel6.setFont(new Font("Dialog", Font.BOLD, 14));
        jLabel8.setFont(new Font("Dialog", Font.BOLD, 14));
        jLabel8.setForeground(new Color(140, 200, 140));
    }

    private void loadRandomImageToButton() {
        try {
            ImageIcon randomIcon = TaiAnhGamePlay.loadRandomImage(
                    btnAnh.getWidth(),
                    btnAnh.getHeight());
            btnAnh.setIcon(randomIcon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

}
