/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import model.KhachHang;
import model.QuanLyKhachHang;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lap top
 */
public class UiKhachHang extends javax.swing.JFrame {

    private List<KhachHang> danhSachKhachHangThat;

    public UiKhachHang() {
        initComponents();
        jPanel1.setOpaque(false);
        taiDanhSachKhachHang();
        cauHinhLabel();
    }

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKhachHang1 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khách hàng trong ngày");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(lblKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(lblKhachHang1)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 400, 400));

        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources-ui/UI_TTKH.png"))); // NOI18N
        getContentPane().add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblKhachHang1;
    // End of variables declaration//GEN-END:variables

    private void taiDanhSachKhachHang() {
        danhSachKhachHangThat = QuanLyKhachHang.getDanhSachKhachHangThat();
    }

    public void reloadKhachHang() {
        taiDanhSachKhachHang();
        cauHinhLabel();
    }

    private void cauHinhLabel() {
        jPanel1.removeAll();

        if (danhSachKhachHangThat.isEmpty()) {
            JLabel emptyLabel = new JLabel("Không có khách hàng nào");
            emptyLabel.setOpaque(false);
            emptyLabel.setForeground(Color.GRAY);
            emptyLabel.setHorizontalAlignment(JLabel.CENTER);
            jPanel1.add(emptyLabel);
        } else {
            jPanel1.setLayout(new GridLayout(danhSachKhachHangThat.size(), 1, 0, 5));

            for (int i = 0; i < danhSachKhachHangThat.size(); i++) {
                KhachHang khachHang = danhSachKhachHangThat.get(i);
                JLabel label = createKhachHangLabel(khachHang, i);
                jPanel1.add(label);
            }
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private JLabel createKhachHangLabel(KhachHang khachHang, int index) {
        JLabel label = new JLabel("<html><center>" + khachHang.getTen() + " Mã: " + khachHang.getMaKH() + "</center></html>");

        label.setOpaque(false);
        label.setForeground(new Color(30, 50, 30));
        label.setFont(new Font("Arial", Font.BOLD, 12));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
        label.setBorder(null);
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                hienThiThongTinKhachHang(danhSachKhachHangThat.get(index));
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                label.setForeground(new Color(0, 100, 200));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                label.setForeground(new Color(30, 30, 30));
            }
        });

        return label;
    }

    private void hienThiThongTinKhachHang(KhachHang khachHang) {
        String thongTin = "<html><div style='text-align: center;'>"
                + "<b style='color: #4682B4; font-size: 16px;'>THÔNG TIN KHÁCH HÀNG THẬT</b><br><br>"
                + "<b>Tên:</b> " + khachHang.getTen() + "<br>"
                + "<b>Tuổi:</b> " + khachHang.getTuoi() + "<br>"
                + "<b>Giới tính:</b> " + khachHang.getGioiTinh() + "<br>"
                + "<b>Mã KH:</b> " + khachHang.getMaKH() + "<br>"
                + "<b>Loại:</b> KHÁCH HÀNG THẬT</div></html>";

        JOptionPane.showMessageDialog(this, thongTin, "Chi Tiết Khách Hàng", JOptionPane.INFORMATION_MESSAGE);
    }
}
