/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.KhachHang;
import model.QuanLyKhachHang;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author lap top
 */
public class UiKhachHang extends javax.swing.JFrame {

    private List<KhachHang> danhSachKhachHangHomNay;
    private JPanel mainPanel, buttonPanel, infoPanel, statsPanel;
    private JLabel titleLabel, statsLabel, infoLabel;
    private JTextArea infoTextArea;
    private JButton refreshButton;

    public UiKhachHang() {
        initComponents();
        setTitle("Quản Lý Khách Hàng");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnKhach1 = new javax.swing.JButton();
        btnKhach2 = new javax.swing.JButton();
        btnKhach3 = new javax.swing.JButton();
        btnKhach4 = new javax.swing.JButton();
        btnKhach5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khách hàng trong ngày");

        btnKhach1.setText("Khách hàng số 1");

        btnKhach2.setText("Khách hàng số 2");

        btnKhach3.setText("Khách hàng số 3");
        btnKhach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhach3ActionPerformed(evt);
            }
        });

        btnKhach4.setText("Khách hàng số 4");

        btnKhach5.setText("Khách hàng số 5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhach1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhach2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhach3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhach5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhach3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhach5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhach1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setText("DAH SÁCH KHÁCH HÀNG HÔM NAY");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhach3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhach1;
    private javax.swing.JButton btnKhach2;
    private javax.swing.JButton btnKhach3;
    private javax.swing.JButton btnKhach4;
    private javax.swing.JButton btnKhach5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
 private void taiDanhSachKhachHang() {
        danhSachKhachHangHomNay = QuanLyKhachHang.taiDanhSachKhachHang();
    }

    private void capNhatGiaoDien() {
        // Clear existing buttons
        buttonPanel.removeAll();

        // Create customer buttons
        for (int i = 0; i < danhSachKhachHangHomNay.size(); i++) {
            KhachHang khachHang = danhSachKhachHangHomNay.get(i);
            JButton button = new JButton(khachHang.getTen());

            // Set different colors for regular customers and ghosts
            if (khachHang.isLaVong()) {
                button.setBackground(new Color(255, 200, 200)); // Light red for ghosts
                button.setForeground(Color.RED);
            } else {
                button.setBackground(new Color(200, 255, 200)); // Light green for regular customers
                button.setForeground(Color.BLUE);
            }

            button.setFont(new Font("Arial", Font.BOLD, 12));
            button.setFocusPainted(false);

            final int index = i;
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    hienThiThongTinKhachHang(danhSachKhachHangHomNay.get(index));
                }
            });

            buttonPanel.add(button);
        }

        // Update statistics
        int soKhachThuong = QuanLyKhachHang.demSoKhachThuong(danhSachKhachHangHomNay);
        int soKhachVong = QuanLyKhachHang.demSoKhachVong(danhSachKhachHangHomNay);
        statsLabel.setText(String.format("Tổng: %d khách | Thường: %d | Vong: %d",
                danhSachKhachHangHomNay.size(), soKhachThuong, soKhachVong));

        // Refresh the UI
        buttonPanel.revalidate();
        buttonPanel.repaint();
        statsPanel.revalidate();
        statsPanel.repaint();
    }

    private void hienThiThongTinKhachHang(KhachHang khachHang) {
        StringBuilder info = new StringBuilder();
        info.append("Tên: ").append(khachHang.getTen()).append("\n");
        info.append("Tuổi: ").append(khachHang.getTuoi()).append("\n");
        info.append("Giới tính: ").append(khachHang.getGioiTinh()).append("\n");
        info.append("Mã KH: ").append(khachHang.getMaKH()).append("\n");
        info.append("Loại: ").append(khachHang.isLaVong() ? "KHÁCH VONG" : "KHÁCH THƯỜNG").append("\n");

        if (khachHang.isLaVong()) {
            info.append("\n⚠️ CẢNH BÁO: Đây là khách vong! ⚠️\n");
            info.append("Hãy cẩn thận khi giao dịch!");
        }

        infoTextArea.setText(info.toString());
    }
}
